### ISSUE TITLE
"n lts" installs v18. suggest 

### ISSUE THREAD

**Issue by friday-mydae** [kadena-community/kadena.js#140] opened 2022-12-25 18:34 UTC
### What article is affected?

https://github.com/kadena-community/kadena.js#installing-prerequisites

### What part(s) of the article would you like to see updated?

Requirements
node > LTS (node 16, as 18 isn't yet LTS)

install node
n lts // installs 18

suggest "n 16" instead

**Comment by ash-vd** [comment] 2022-12-25 21:30
Duplicate of #141

**Closed by ash-vd** 2022-12-25 21:30 UTC
